param()
$ErrorActionPreference = 'Stop'
function Run-Case($name, $overrides){
  Write-Host "Running $name..."
  $json = & powershell -ExecutionPolicy Bypass -Command "& { .\scripts\Run-Mt5Backtest.ps1 -RunName '$name' -Symbol 'XAUUSD_CSV' -FromDate '2016.02.17' -ToDate '2026.02.17' -Model 1 -Override @('$($overrides -join "','")') }"
  $obj = $json | ConvertFrom-Json
  [pscustomobject]@{
    run_name = $obj.run_name
    net = [double]$obj.total_net_profit
    pf = [double]$obj.profit_factor
    trades = [int]$obj.total_trades
    balance_dd = $obj.balance_drawdown_raw
    equity_dd = $obj.equity_drawdown_raw
    report = $obj.report_path
  }
}
$cases = @(
  @{ Name='csv10y_lq_01_base'; Ov=@('InpTradingMode=1','InpConfigTemplate=2','Debug=0') },
  @{ Name='csv10y_lq_02_session_6_18'; Ov=@('InpTradingMode=1','InpConfigTemplate=2','Debug=0','InpTradeStartHour=6','InpTradeEndHour=18') },
  @{ Name='csv10y_lq_03_spread_on'; Ov=@('InpTradingMode=1','InpConfigTemplate=2','Debug=0','InpUseSpreadFilter=true','InpMaxSpreadAtrFrac=0.20') },
  @{ Name='csv10y_lq_04_manual_selective'; Ov=@('InpTradingMode=1','InpConfigTemplate=0','Debug=0','InpRiskPct=0.08','InpMaxTradesPerDay=40','InpMaxConsecLosses=4','InpMaxDailyDDPct=4.0','InpUseSessionFilter=true','InpTradeStartHour=6','InpTradeEndHour=21','InpUseSpreadFilter=true','InpMaxSpreadAtrFrac=0.20','InpUseDynamicSpreadGate=true','InpSpreadMedianLen=200','InpSpreadMedianMult=1.80','InpOnePosPerSymbol=true','InpAtrFilterMult=0.95','InpUseBreakEven=true','InpBreakEvenAtrTrigger=0.45','InpBreakEvenOffsetPoints=4','InpTrailStartAtr=0.90','InpTrailAtrMult=1.10','InpLqSwingLookback=12','InpLqSweepBufferAtr=0.08','InpLqSweepMaxAgeBars=5','InpLqMinDisplacementAtr=0.80','InpLqMssLookback=4','InpLqStopBufferAtr=0.22','InpLqTpR=1.20','InpLqEntryMode=2','InpLqRetestMaxAgeBars=3','InpLqRetestTolAtr=0.08','InpLqAllowStopFallback=true','InpLqUseStructuralTrail=true','InpLqStructuralTrailAtr=0.30') },
  @{ Name='csv10y_lq_05_manual_selective2'; Ov=@('InpTradingMode=1','InpConfigTemplate=0','Debug=0','InpRiskPct=0.08','InpMaxTradesPerDay=30','InpMaxConsecLosses=4','InpMaxDailyDDPct=4.0','InpUseSessionFilter=true','InpTradeStartHour=6','InpTradeEndHour=18','InpUseSpreadFilter=true','InpMaxSpreadAtrFrac=0.18','InpUseDynamicSpreadGate=true','InpSpreadMedianLen=200','InpSpreadMedianMult=1.70','InpOnePosPerSymbol=true','InpAtrFilterMult=1.00','InpUseBreakEven=true','InpBreakEvenAtrTrigger=0.50','InpBreakEvenOffsetPoints=5','InpTrailStartAtr=1.00','InpTrailAtrMult=1.15','InpLqSwingLookback=14','InpLqSweepBufferAtr=0.10','InpLqSweepMaxAgeBars=4','InpLqMinDisplacementAtr=0.95','InpLqMssLookback=4','InpLqStopBufferAtr=0.25','InpLqTpR=1.10','InpLqEntryMode=2','InpLqRetestMaxAgeBars=3','InpLqRetestTolAtr=0.07','InpLqAllowStopFallback=true','InpLqUseStructuralTrail=true','InpLqStructuralTrailAtr=0.28') },
  @{ Name='csv10y_lq_06_manual_rr'; Ov=@('InpTradingMode=1','InpConfigTemplate=0','Debug=0','InpRiskPct=0.06','InpMaxTradesPerDay=35','InpMaxConsecLosses=4','InpMaxDailyDDPct=4.0','InpUseSessionFilter=true','InpTradeStartHour=6','InpTradeEndHour=21','InpUseSpreadFilter=true','InpMaxSpreadAtrFrac=0.22','InpUseDynamicSpreadGate=true','InpSpreadMedianLen=200','InpSpreadMedianMult=1.80','InpOnePosPerSymbol=true','InpAtrFilterMult=0.95','InpUseBreakEven=false','InpTrailStartAtr=1.30','InpTrailAtrMult=1.15','InpLqSwingLookback=10','InpLqSweepBufferAtr=0.06','InpLqSweepMaxAgeBars=5','InpLqMinDisplacementAtr=0.90','InpLqMssLookback=3','InpLqStopBufferAtr=0.28','InpLqTpR=1.50','InpLqEntryMode=2','InpLqRetestMaxAgeBars=3','InpLqRetestTolAtr=0.08','InpLqAllowStopFallback=true','InpLqUseStructuralTrail=true','InpLqStructuralTrailAtr=0.32') },
  @{ Name='csv10y_lq_07_manual_rr2'; Ov=@('InpTradingMode=1','InpConfigTemplate=0','Debug=0','InpRiskPct=0.06','InpMaxTradesPerDay=25','InpMaxConsecLosses=3','InpMaxDailyDDPct=3.5','InpUseSessionFilter=true','InpTradeStartHour=7','InpTradeEndHour=18','InpUseSpreadFilter=true','InpMaxSpreadAtrFrac=0.18','InpUseDynamicSpreadGate=true','InpSpreadMedianLen=200','InpSpreadMedianMult=1.60','InpOnePosPerSymbol=true','InpAtrFilterMult=1.00','InpUseBreakEven=false','InpTrailStartAtr=1.40','InpTrailAtrMult=1.20','InpLqSwingLookback=14','InpLqSweepBufferAtr=0.10','InpLqSweepMaxAgeBars=4','InpLqMinDisplacementAtr=1.05','InpLqMssLookback=4','InpLqStopBufferAtr=0.30','InpLqTpR=1.40','InpLqEntryMode=2','InpLqRetestMaxAgeBars=2','InpLqRetestTolAtr=0.07','InpLqAllowStopFallback=true','InpLqUseStructuralTrail=true','InpLqStructuralTrailAtr=0.30') },
  @{ Name='csv10y_lq_08_manual_sparse'; Ov=@('InpTradingMode=1','InpConfigTemplate=0','Debug=0','InpRiskPct=0.05','InpMaxTradesPerDay=20','InpMaxConsecLosses=3','InpMaxDailyDDPct=3.0','InpUseSessionFilter=true','InpTradeStartHour=7','InpTradeEndHour=18','InpUseSpreadFilter=true','InpMaxSpreadAtrFrac=0.16','InpUseDynamicSpreadGate=true','InpSpreadMedianLen=200','InpSpreadMedianMult=1.55','InpOnePosPerSymbol=true','InpAtrFilterMult=1.05','InpUseBreakEven=true','InpBreakEvenAtrTrigger=0.55','InpBreakEvenOffsetPoints=6','InpTrailStartAtr=1.00','InpTrailAtrMult=1.20','InpLqSwingLookback=16','InpLqSweepBufferAtr=0.12','InpLqSweepMaxAgeBars=4','InpLqMinDisplacementAtr=1.10','InpLqMssLookback=5','InpLqStopBufferAtr=0.32','InpLqTpR=1.20','InpLqEntryMode=2','InpLqRetestMaxAgeBars=2','InpLqRetestTolAtr=0.06','InpLqAllowStopFallback=true','InpLqUseStructuralTrail=true','InpLqStructuralTrailAtr=0.28') },
  @{ Name='csv10y_lq_09_manual_market'; Ov=@('InpTradingMode=1','InpConfigTemplate=0','Debug=0','InpRiskPct=0.06','InpMaxTradesPerDay=30','InpMaxConsecLosses=3','InpMaxDailyDDPct=4.0','InpUseSessionFilter=true','InpTradeStartHour=6','InpTradeEndHour=18','InpUseSpreadFilter=true','InpMaxSpreadAtrFrac=0.18','InpUseDynamicSpreadGate=true','InpSpreadMedianLen=200','InpSpreadMedianMult=1.60','InpOnePosPerSymbol=true','InpAtrFilterMult=1.00','InpUseBreakEven=true','InpBreakEvenAtrTrigger=0.45','InpBreakEvenOffsetPoints=5','InpTrailStartAtr=0.95','InpTrailAtrMult=1.15','InpLqSwingLookback=12','InpLqSweepBufferAtr=0.08','InpLqSweepMaxAgeBars=4','InpLqMinDisplacementAtr=0.95','InpLqMssLookback=4','InpLqStopBufferAtr=0.26','InpLqTpR=1.15','InpLqEntryMode=0','InpLqRetestMaxAgeBars=2','InpLqRetestTolAtr=0.07','InpLqAllowStopFallback=true','InpLqUseStructuralTrail=true','InpLqStructuralTrailAtr=0.30') },
  @{ Name='csv10y_lq_10_manual_hybrid'; Ov=@('InpTradingMode=1','InpConfigTemplate=0','Debug=0','InpRiskPct=0.06','InpMaxTradesPerDay=30','InpMaxConsecLosses=3','InpMaxDailyDDPct=4.0','InpUseSessionFilter=true','InpTradeStartHour=6','InpTradeEndHour=20','InpUseSpreadFilter=true','InpMaxSpreadAtrFrac=0.18','InpUseDynamicSpreadGate=true','InpSpreadMedianLen=200','InpSpreadMedianMult=1.60','InpOnePosPerSymbol=true','InpAtrFilterMult=0.98','InpUseBreakEven=true','InpBreakEvenAtrTrigger=0.45','InpBreakEvenOffsetPoints=5','InpTrailStartAtr=0.95','InpTrailAtrMult=1.15','InpLqSwingLookback=12','InpLqSweepBufferAtr=0.08','InpLqSweepMaxAgeBars=4','InpLqMinDisplacementAtr=0.90','InpLqMssLookback=4','InpLqStopBufferAtr=0.26','InpLqTpR=1.20','InpLqEntryMode=2','InpLqRetestMaxAgeBars=2','InpLqRetestTolAtr=0.07','InpLqAllowStopFallback=true','InpLqUseStructuralTrail=true','InpLqStructuralTrailAtr=0.30') }
)
$results = foreach($case in $cases){ Run-Case $case.Name $case.Ov }
$sorted = $results | Sort-Object @{Expression='net';Descending=$true}, @{Expression='pf';Descending=$true}, @{Expression='trades';Descending=$true}
$sorted | ConvertTo-Json -Depth 4 | Set-Content -Encoding ascii '.\mt5-portable\reports\csv10y_liquidity_search.json'
$sorted | Format-Table -AutoSize | Out-String | Set-Content -Encoding ascii '.\mt5-portable\reports\csv10y_liquidity_search.txt'
Get-Content '.\mt5-portable\reports\csv10y_liquidity_search.txt'
